feedback/urls.py
from django.contrib import admin
from django.urls import path
from .views import testi, filter_star

app_name = 'feedback'
urlpatterns = [
    path('',testi, name ='Testimoni'),
    path('filter', filter_star, name = "pilih_star" )
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('',views.order, name = 'order'),
    path('calculate',views.calculate_harga, name = 'calculate'),
    path('pengeluaran',views.calculate_total_pengeluaran, name = 'calculate'),

]

tugas_ppw_kel_lulus_a/urls.py
from django.contrib import admin
from django.urls import path, include
# from . import views
# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
    path('', include('user_laundry.urls')),
    path('laundryadmin/', include('laundryadmin.urls')),
    path('feedback/', include('feedback.urls')),
    path('status/', include('status.urls')),
]

feedback/models.py
from django.db import models

# Create your models here.
class Feedback(models.Model):

    Comment = models.CharField(max_length=50)
    bintang= models.IntegerField(default=0)
    date= models.DateTimeField(auto_now=True)
    nama=models.CharField(max_length=20, default= "Rafa")

feedback/forms.py
from django import forms
from .models import Feedback

class CommentForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['Comment', 'bintang']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
             })

feedback/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Feedback
from user_laundry.models import userLaundry
from .forms import *
from django.core import serializers
# from django.views.decorators.http import login_required

# @login_required
def testi(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            pelanggan = request.user.username
            form = CommentForm(request.POST)
            if form.is_valid():
                testi = form.save()
                testi.nama = pelanggan
                testi.save()
            return redirect('feedback:Testimoni')
            pass
        else:
            form = CommentForm()
            return render(request, 'Feedback.html', {'form': form, 'list_testimoni' : Feedback.objects.all()})
    else:
        return redirect("/")

def filter_star(request):
    star = request.GET["star"]
    if star == "all":
        data = serializers.serialize('json', Feedback.objects.all(), fields=("Comment","bintang","nama","date"))
        data = eval(data)
        return JsonResponse({"items": data}, safe= False)
    if star == "1":
        data = serializers.serialize('json', Feedback.objects.filter(bintang = 1), fields=("Comment","bintang","nama","date"))
        data = eval(data)
        return JsonResponse({"items": data}, safe= False)
        
    if star == "2":
        data = serializers.serialize('json', Feedback.objects.filter(bintang = 2), fields=("Comment","bintang","nama","date"))
        data = eval(data)
        return JsonResponse({"items": data}, safe= False)
    if star == "3":
        data = serializers.serialize('json', Feedback.objects.filter(bintang = 3), fields=("Comment","bintang","nama","date"))
        data = eval(data)
        return JsonResponse({"items": data}, safe= False)
    if star == "4":
        data = serializers.serialize('json', Feedback.objects.filter(bintang = 4), fields=("Comment","bintang","nama","date"))
        data = eval(data)
        return JsonResponse({"items": data}, safe= False)
    if star == "5":
        data = serializers.serialize('json', Feedback.objects.filter(bintang = 5), fields=("Comment","bintang","nama","date"))
        data = eval(data)
        return JsonResponse({"items": data}, safe= False)
    

feedback/templates/Feedback.html
{% extends "navbar_user.html" %}
{% load static from staticfiles %}
{% block content %}
    <style type="text/css">
    .rat{
            width:93%;
            max-width: 350px;
            text-align: center;
            margin: 4% auto;
            padding: 40px 0;
            border-radius: 5px;
            overflow:hidden ;
            margin-bottom: 25px;
        }
        div.stars{
            width: 270px;
            display:inline-block;
        }
        input.star{
            display: none;
        }
        label.star{
            float: right;
            padding: 5px;
            font-size: 36px;
            color: #444;
            transition:  all 0.2s;
        }
        input.star:checked ~ label.star:before{
            content: '\f005';
            color: #fd4;
            transition: all 0.2s;
        }
        input.star-5:checked ~ label.star:before{
            color: #fe7;
            text-shadow: 0 0 20px #952;
        }
        label.star:before{
            content:'\f006' ;
            font-family:  fontAwesome;
        }
        input.star-1:checked ~label.star:before{
            color: #ff6622;
        }
        .bg-light{
            background-color: transparent !important;
        }
        
    body{
        height: 100%;
        margin: 0;
    }
    </style>

    <script src="http://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="{% static 'feedback.js' %}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
<div style="background: #AAB4D2;width: 100%;">
      <div class="rat">
         <p style="margin-left:2VW;">HOW WAS THE SERVICE?</p>
    <div class="stars">
        <form action="">
            <input type="radio" class="star star-5" id="star-5"onclick="bintang5()" name="star">
            <label for="star-5" class="star star-5"></label>

            <input type="radio" class="star star-5" id="star-4" onclick="bintang4()" name="star">
            <label for="star-4" class="star star-5"></label>

            <input type="radio" class="star star-5" id="star-3" onclick="bintang3()"name="star">
            <label for="star-3" class="star star-5"></label>

            <input type="radio" class="star star-5" id="star-2" onclick="bintang2()" name="star">
            <label for="star-2" class="star star-5"></label>

            <input type="radio" class="star star-5" id="star-1" onclick="bintang1()" name="star">
            <label for="star-1" class="star star-5"></label>
        </form>
    </div>
</div>
      <div class="container" style="font-family: 'Chaparral Pro', cursive;">
        <hr style="margin-top: 1%;">
        <form action="" method="post">
          {% csrf_token %}
          <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10">
                <label for="id_Comment">Comment:</label>
                <br>
                {{form.Comment}}
                <div style="display: none;">
                <label for="id_bintang">bintang</label>
                <br>
                {{form.bintang}}
                </div>  
            </div>
          </div>
          <div class="form-row">
            <div class="col-sm-1"></div>
            <input
              class="btn"
              type="submit"
              value="SUBMIT"
              name="tombol"
              id = "tombol"
              style="margin-top:3%; background:#D7E0F9; color:black"
            />
          </div>
        </form>
                <div id= "filter"style="margin-left: 7vw; margin-right: 10vw;">
                <br>
                <button id ="comments_all" style="background: transparent;" class= "btn btn-lg-2 mt-2" 
                    type="submit">All</button>
                <button id ="comments_1" style="background: transparent" class= "btn btn-lg-2 mt-2" 
                    type="submit"><i class="fas fa-star"></i></button>
                <button id ="comments_2" style="background: transparent;" class= "btn btn-lg-2 mt-2" 
                    type="submit"><i class="fas fa-star"></i><i class="fas fa-star"></i></button>
                <button id ="comments_3" style="background: transparent;" class= "btn btn-lg-2 mt-2" 
                    type="submit"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></i></button>
                <button id ="comments_4" style="background: transparent;" class= "btn btn-lg-2 mt-2" 
                    type="submit"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></button>
                <button id ="comments_5" style="background: transparent;" class= "btn btn-lg-2 mt-2" 
                    type="submit"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></button>
                <!-- {% for hasil in list_testimoni %}
                <a>{{hasil.date}}</a>  <br>
                <a>{{hasil.nama}}</a>  <br>
                <a><p>-rate:{{hasil.bintang}}</p></a>
                <a><p>"{{hasil.Comment}} "</p></a>
                {%endfor %} -->
        </div>
        <div id="comments" class="kotak-status mt-5" style="width: 80%; margin-left: 7vw; margin-right: 10vw;" ></div>
    </div>
      {% endblock %}