order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('',views.order, name = 'order'),
    path('calculate',views.calculate_harga, name = 'calculate'),
    path('pengeluaran',views.calculate_total_pengeluaran, name = 'calculate'),

]

tugas_ppw_kel_lulus_a/urls.py
from django.contrib import admin
from django.urls import path, include
# from . import views
# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
    path('', include('user_laundry.urls')),
    path('laundryadmin/', include('laundryadmin.urls')),
    path('feedback/', include('feedback.urls')),
    path('status/', include('status.urls')),
]

user_laundry/urls.py
from django.urls import path
from . import views 

#url for app

app_name = 'user_laundry'

urlpatterns = [
    path('',views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('show/',views.show,name='show'),
    path('',views.logout,name='logout'),
]

user_laundry/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

#  This will auto create a profile of user with blank phone number that can be updated later.

class userLaundry(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default = 1)
    address = models.CharField(max_length=50, default = 'Jalan Duren')
    number = models.BigIntegerField(default = 298721)

#     @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         userLaundry.objects.create(user=instance)

user_laundry/forms.py
from django.db import models
from django import forms
from .models import userLaundry
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class registerForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Please enter your name')
    last_name = forms.CharField(max_length=30, required=False, help_text='Please enter your name')
    address = forms.CharField(max_length=100, required=False, help_text='Please enter your address')
    number = forms.IntegerField(required=False, help_text='Please enter your number')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username','address','number', 'password1', 'password2', )

user_laundry/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import userLaundry
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from .forms import registerForm
import requests
import json

# Create your views here.

def homepage(request):
    if request.method == "POST":
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            print(user)
            login(request, user)
            return redirect('user_laundry:show')
    else:
        form = AuthenticationForm()
    return render(request, "Homepage.html", {"form" : form })


def register(request):
    if request.method == 'POST':
        form_regis = registerForm(request.POST)
        if form_regis.is_valid():
            x = form_regis.save(commit = False)
            x.first_name = form_regis.cleaned_data.get('first_name')
            x.last_name = form_regis.cleaned_data.get('last_name')
            x.save()

            address1 = form_regis.cleaned_data.get('address')
            number1 = form_regis.cleaned_data.get('number')
            user_laundry = userLaundry(address = address1, number = number1)
            user_laundry.user = x
            user_laundry.save()

            x.save()
            print(x.userlaundry)
            return redirect('user_laundry:homepage')
    else:
        form_regis = registerForm()
    return render(request, "register.html", {'form': form_regis})


def show(request):
    username_login = request.user.username
    return render(request,'Show.html',{'name' : username_login, "navbar" : True})

def logout(request):
    return render(request,'Homepage.html')

user_laundry/templates/Homepage.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100 " src="{% static 'homepage.jpg' %}" alt="First slide">
            <div class="carousel-caption mr-auto">
                <p class="h1">We offer you <br> The Best Laundry Service</p>
                <p class="h5">Save time,enjoy your time</p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'photo4.jpg' %}" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'photo3.jpg' %}" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
  </div>

  <div id="about" class="table-responsive">
    <table class="table table-borderless">
            <thead>
              <tr>
                <th scope="col">About Us</th>
                <th scope="col">Login</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th>Our Laundry Service is a convenient and affordable 
                        of sending out your loundry to be done by proffesional.
                        We take care of your laundry and dry cleaning with a push of a button from your phone or through our website.
                        We strive to make cleaning your clothes a seamless experience and we will cater to your schedule.
                        Come straight to your door to pick up and deliver your laundry at affordable price.
                <td>
                  <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                      {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                      <small class="text-muted">Don't have an account? <a href="{% url 'user_laundry:register' %}">Sign Up Now</a></small>
                    </div>
                    <div class="border-top pt-3">
                        <button id = "but-login" class="button" type="submit" style="margin-left: 250px;">Submit</button>
                    </div>
                  </form>
                </td>
                <td>
                  <p>Banyaknya Pelanggan yang sudah mendaftar :</p>
                </td>
                </th>
              </tr>
            </tbody>
    </table>
    </div>
  </div>
{% endblock %}

user_laundry/templates/Show.html
{% extends "base.html" %}
{% load static %}
{% block content %}
        <div class="Regist">
            <h2>Hi {{name}} !</h2>
            <h3>
                Selamat! Anda telah berhasil melakukan registrasi!
                Selanjutnya anda bisa melakukan pemesanan.
            </h3>
        </div>
{% endblock %}

user_laundry/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
        <link rel="stylesheet" type="text/css" href = "{% static 'dataPelanggan/homepage.css' %}">
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
        <script src="{% static 'dataPelanggan/homepage.js' %}"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Lora|Roboto&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      
    </head>
<body style="background-color: #AAB4D2;"><script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>>
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}
</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


</html>

user_laundry/templates/navbar.html
{% load static %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top navbar-user" style="padding: .7rem 1rem;">
        <a class="navbar-brand brand" href=""><b><i>MyLaundry</i></b></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse topnav"  id="navbarResponsive">
                <ul class="navbar-nav mr-auto w-100 d-flex justify-content-end" style="letter-spacing: 2px;">
                    {% if navbar == True %}
                    <li class="nav-item">
                        <a class="nav-link active" href="#">Status</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#">Pemesanan</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#">Testimoni</a>
                    </li>
                    <li class="nav-item">
                        <a id = "click-logout" class="nav-link active" href="{% url 'user_laundry:homepage' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="#about" class="slide-section">About Us</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
                   
    </nav>

user_laundry/templates/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-groupregist">
                <legend class="border-bottom mb-4">Let's Join Now!</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-groupregist">
                <button id = "reg" class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'user_laundry:homepage' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock %}