order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('',views.order, name = 'order'),
    path('calculate',views.calculate_harga, name = 'calculate'),
    path('pengeluaran',views.calculate_total_pengeluaran, name = 'calculate'),

]

tugas_ppw_kel_lulus_a/urls.py
from django.contrib import admin
from django.urls import path, include
# from . import views
# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
    path('', include('user_laundry.urls')),
    path('laundryadmin/', include('laundryadmin.urls')),
    path('feedback/', include('feedback.urls')),
    path('status/', include('status.urls')),
]

user_laundry/urls.py
from django.urls import path
from . import views 

#url for app

app_name = 'user_laundry'

urlpatterns = [
    path('',views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('show/',views.show,name='show'),
    path('',views.logout,name='logout'),
]

templates/navbar_user.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href = "{% static 'order.css' %}">
    <link rel="stylesheet" type="text/css" href = "{% static 'navbar.css' %}">
    <link rel="stylesheet" type="text/css" href = "{% static 'laundryadmin.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora|Roboto&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/4b60c8a34d.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
</head>
<body style="background-color: #AAB4D2;">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top navbar-user" style="padding: .7rem 1rem;">
        <a class="navbar-brand brand" href="#"><b><i>MyLaundry</i></b></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse topnav"  id="navbarResponsive">
            <ul class="navbar-nav mr-auto w-100 d-flex justify-content-end" style="letter-spacing: 2px;">
                <li class="nav-item">
                    <a class="nav-link active" href="#">Beranda</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#">Status</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#">Pemesanan</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#">Testimoni</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'user_laundry:homepage' %}">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="{% static 'photo2.jpg' %}" alt="First slide">
                <div class="carousel-caption d-none d-md-block">
                    <p class="h1" style="color: black; font-weight: bold; font-family: 'Lora';">We offer you the Best <br> Laundry Service</p>
                    <p class="h5" style="color: black; font-family: 'Lora';">Save time,enjoy your time</p>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'photo4.jpg' %}" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'photo3.jpg' %}" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
      </div>
    {% block content  %}
    {% endblock  %}
</body>
<<<<<<< Updated upstream
=======
<!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->
<script src="{% static 'Order.js' %}"></script>
>>>>>>> Stashed changes
<script>
    function bintang1(){
        document.getElementById("id_bintang").value = 1;
    }
    function bintang2(){
        document.getElementById("id_bintang").value = 2;
    }
    function bintang3(){
        document.getElementById("id_bintang").value = 3;
    }
    function bintang4(){
        document.getElementById("id_bintang").value = 4;
    }
    function bintang5(){
        document.getElementById("id_bintang").value = 5;
    }
</script>
</html>